<?php

namespace Database\Seeders;

use App\Models\Route;
use Illuminate\Database\Seeder;

class RouteSeeder extends Seeder
{
    public function run(): void
    {
        $routes = [
            [
                'zone_id' => 1,
                'category_id' => 1,
                'name' => 'Sendero Los Quetzales',
                'slug' => 'sendero-los-quetzales',
                'description' => 'Uno de los senderos más emblemáticos de Panamá. Atraviesa bosque nuboso desde Boquete hasta Cerro Punta con avistamiento del quetzal, orquídeas y paisajes de montaña. El recorrido completo toma de 6 a 8 horas entre los dos extremos.',
                'difficulty' => 'moderado',
                'duration_minutes' => 480,
                'distance_km' => 14.5,
                'elevation_gain_m' => 850,
                'start_lat' => 8.7800000,
                'start_lng' => -82.4500000,
                'cover_image' => 'https://placehold.co/800x600/2563eb/ffffff?text=Sendero+Los+Quetzales',
                'tips' => ['Llevar impermeable', 'Iniciar temprano (6:00 AM)', 'Llevar suficiente agua y snacks', 'Usar calzado de montaña', 'Contratar guía local recomendado'],
                'is_active' => true,
            ],
            [
                'zone_id' => 2,
                'category_id' => 1,
                'name' => 'Ascenso al Volcán Barú',
                'slug' => 'ascenso-al-volcan-baru',
                'description' => 'Subida al punto más alto de Panamá (3,474 msnm). Desde la cima se puede ver el océano Pacífico y el Mar Caribe simultáneamente en días despejados. Existen dos rutas de ascenso: por Boquete y por Volcán.',
                'difficulty' => 'difícil',
                'duration_minutes' => 720,
                'distance_km' => 22.0,
                'elevation_gain_m' => 1800,
                'start_lat' => 8.8075000,
                'start_lng' => -82.5428000,
                'cover_image' => 'https://placehold.co/800x600/16a34a/ffffff?text=Volcan+Baru',
                'tips' => ['Ascenso nocturno recomendado para ver el amanecer', 'Temperaturas bajo cero en la cima', 'Permiso del MINSA requerido', 'Llevar linterna frontal', 'Guía obligatorio'],
                'is_active' => true,
            ],
            [
                'zone_id' => 1,
                'category_id' => 3,
                'name' => 'Cascada Escondida',
                'slug' => 'cascada-escondida',
                'description' => 'Hermosa cascada de 25 metros de caída rodeada de bosque tropical. El sendero de acceso es corto pero empinado, con pozas naturales ideales para nadar. Muy popular entre turistas y locales.',
                'difficulty' => 'fácil',
                'duration_minutes' => 90,
                'distance_km' => 2.0,
                'elevation_gain_m' => 120,
                'start_lat' => 8.7732000,
                'start_lng' => -82.4610000,
                'cover_image' => 'https://placehold.co/800x600/0284c7/ffffff?text=Cascada+Escondida',
                'tips' => ['Llevar traje de baño', 'Sendero resbaloso en época lluviosa', 'Entrada tiene costo', 'Llegar temprano para evitar multitudes'],
                'is_active' => true,
            ],
            [
                'zone_id' => 4,
                'category_id' => 5,
                'name' => 'Termales de Caldera',
                'slug' => 'termales-de-caldera',
                'description' => 'Aguas termales naturales a orillas del río Caldera. Pozas de diferentes temperaturas con propiedades minerales. Ambiente relajado rodeado de vegetación tropical. Ideal después de una caminata.',
                'difficulty' => 'fácil',
                'duration_minutes' => 120,
                'distance_km' => 0.5,
                'elevation_gain_m' => 20,
                'start_lat' => 8.6680000,
                'start_lng' => -82.2990000,
                'cover_image' => 'https://placehold.co/800x600/d97706/ffffff?text=Termales+Caldera',
                'tips' => ['Llevar toalla y traje de baño', 'Hidratarse bien', 'No apto para niños muy pequeños por temperatura', 'Hay servicio de vestidores'],
                'is_active' => true,
            ],
            [
                'zone_id' => 1,
                'category_id' => 2,
                'name' => 'Ruta del Café de Boquete',
                'slug' => 'ruta-del-cafe-de-boquete',
                'description' => 'Recorrido por las fincas cafetaleras más prestigiosas de Boquete. Incluye explicación del proceso de cultivo, cosecha, tueste y cata de café geisha y variedades especiales. Varias fincas ofrecen tours guiados.',
                'difficulty' => 'fácil',
                'duration_minutes' => 180,
                'distance_km' => 4.0,
                'elevation_gain_m' => 100,
                'start_lat' => 8.7750000,
                'start_lng' => -82.4500000,
                'cover_image' => 'https://placehold.co/800x600/92400e/ffffff?text=Ruta+del+Cafe',
                'tips' => ['Reservar con anticipación', 'Preguntar por la cata de geisha', 'Usar zapatos cómodos', 'Llevar efectivo para compras'],
                'is_active' => true,
            ],
            [
                'zone_id' => 4,
                'category_id' => 6,
                'name' => 'Rafting en Río Chiriquí',
                'slug' => 'rafting-en-rio-chiriqui',
                'description' => 'Aventura de rafting en aguas bravas del río Chiriquí con rápidos clase II-IV. El descenso recorre cañones rodeados de selva tropical. Guías certificados y equipo de seguridad incluido.',
                'difficulty' => 'moderado',
                'duration_minutes' => 240,
                'distance_km' => 12.0,
                'elevation_gain_m' => 200,
                'start_lat' => 8.5530000,
                'start_lng' => -82.2130000,
                'cover_image' => 'https://placehold.co/800x600/0d9488/ffffff?text=Rafting+Chiriqui',
                'tips' => ['Edad mínima 12 años', 'Saber nadar es obligatorio', 'Llevar ropa cómoda que se moje', 'Proteger cámaras con funda impermeable', 'Repelente de insectos'],
                'is_active' => true,
            ],
            [
                'zone_id' => 6,
                'category_id' => 4,
                'name' => 'Playa Las Lajas',
                'slug' => 'playa-las-lajas',
                'description' => 'Extensa playa de arena volcánica oscura de más de 10 km de longitud. Oleaje moderado ideal para surf, bodysurf y paseos a caballo. Atardeceres espectaculares con palmeras y restaurantes de mariscos.',
                'difficulty' => 'fácil',
                'duration_minutes' => 180,
                'distance_km' => 1.0,
                'elevation_gain_m' => 0,
                'start_lat' => 8.2150000,
                'start_lng' => -81.8770000,
                'cover_image' => 'https://placehold.co/800x600/0ea5e9/ffffff?text=Playa+Las+Lajas',
                'tips' => ['Protector solar biodegradable', 'Llevar efectivo (pocos ATM)', 'Mejor época: diciembre a abril', 'Probar el ceviche local', 'Cabañas disponibles para hospedarse'],
                'is_active' => true,
            ],
            [
                'zone_id' => 7,
                'category_id' => 4,
                'name' => 'Boca Chica y sus Islas',
                'slug' => 'boca-chica-y-sus-islas',
                'description' => 'Pueblo pesquero con acceso a un archipiélago de islas vírgenes. Islas como Boca Brava, Game y San José ofrecen playas solitarias, snorkel y pesca deportiva. Paseos en lancha desde el muelle local.',
                'difficulty' => 'fácil',
                'duration_minutes' => 360,
                'distance_km' => 5.0,
                'elevation_gain_m' => 0,
                'start_lat' => 8.1180000,
                'start_lng' => -81.7880000,
                'cover_image' => 'https://placehold.co/800x600/0891b2/ffffff?text=Boca+Chica',
                'tips' => ['Llevar snorkel', 'Repelente de insectos obligatorio', 'Negociar precio del paseo en lancha', 'Llevar comida y bebida', 'Protector solar'],
                'is_active' => true,
            ],
            [
                'zone_id' => 5,
                'category_id' => 10,
                'name' => 'Mirador de Cerro Punta',
                'slug' => 'mirador-de-cerro-punta',
                'description' => 'Camino panorámico que recorre las cumbres de Tierras Altas con vistas al valle de Cerro Punta, las plantaciones de hortalizas y fresas, y el macizo del Volcán Barú de fondo. Ideal para fotografía.',
                'difficulty' => 'fácil',
                'duration_minutes' => 120,
                'distance_km' => 4.5,
                'elevation_gain_m' => 150,
                'start_lat' => 8.8500000,
                'start_lng' => -82.6000000,
                'cover_image' => 'https://placehold.co/800x600/65a30d/ffffff?text=Cerro+Punta',
                'tips' => ['Llevar abrigo (clima frío)', 'Comprar fresas frescas en el camino', 'Visitar el mercado de productores', 'Mejor luz para fotos al atardecer'],
                'is_active' => true,
            ],
            [
                'zone_id' => 4,
                'category_id' => 3,
                'name' => 'Cascada Los Chorros',
                'slug' => 'cascada-los-chorros',
                'description' => 'Imponente caída de agua de 40 metros en medio de la selva de Gualaca. La poza natural al pie es perfecta para nadar. El acceso requiere caminata de 30 minutos por sendero de selva tropical.',
                'difficulty' => 'moderado',
                'duration_minutes' => 150,
                'distance_km' => 3.0,
                'elevation_gain_m' => 180,
                'start_lat' => 8.5330000,
                'start_lng' => -82.2330000,
                'cover_image' => 'https://placehold.co/800x600/0f766e/ffffff?text=Cascada+Los+Chorros',
                'tips' => ['Llevar traje de baño', 'Sendero fangoso', 'Llevar agua', 'No dejar basura', 'Recomendado con guía local'],
                'is_active' => true,
            ],
        ];

        foreach ($routes as $route) {
            Route::create($route);
        }
    }
}
